# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.detected_object import DetectedObject  # noqa: F401,E501
from swagger_server import util


class ApiResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, detected_objects: List[DetectedObject]=None):  # noqa: E501
        """ApiResponse - a model defined in Swagger

        :param detected_objects: The detected_objects of this ApiResponse.  # noqa: E501
        :type detected_objects: List[DetectedObject]
        """
        self.swagger_types = {
            'detected_objects': List[DetectedObject]
        }

        self.attribute_map = {
            'detected_objects': 'detectedObjects'
        }

        self._detected_objects = detected_objects

    @classmethod
    def from_dict(cls, dikt) -> 'ApiResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiResponse of this ApiResponse.  # noqa: E501
        :rtype: ApiResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detected_objects(self) -> List[DetectedObject]:
        """Gets the detected_objects of this ApiResponse.


        :return: The detected_objects of this ApiResponse.
        :rtype: List[DetectedObject]
        """
        return self._detected_objects

    @detected_objects.setter
    def detected_objects(self, detected_objects: List[DetectedObject]):
        """Sets the detected_objects of this ApiResponse.


        :param detected_objects: The detected_objects of this ApiResponse.
        :type detected_objects: List[DetectedObject]
        """

        self._detected_objects = detected_objects
